#!/usr/bin/env bash

set -eEuo pipefail
shopt -s inherit_errexit

result=$( security dump-keychain | awk -F'=' '/0x00000007/ { print $2 }' | sed 's/^"//; s/"$//;' | grep -vwe '<NULL>' | fzf --query "${*}" --select-1 )
get-secret "$result"
