#!/usr/bin/env bash

length="${1:-64}"

password=$( openssl rand -base64 5000 |
    tr -dc '[a-zA-Z0-9]' |
    tr '[:upper:]' '[:lower:]'  |
    tr -d 'fcgsCFSG' | # Most bad words have an f or s in them, so just dump those
    tr -d '50oOlLI1Z2' ) # Confusing characters

pass=""
seperator="_"

start_index=1
while [[ ${#pass} -lt $length ]]; do
    start_index=$(( start_index + 4 ))
    next_group=$( echo "$password" | cut -c $start_index-$(( start_index + ( RANDOM % 3 + 2 ) )) )
    pass="${pass}${pass:+$seperator}${next_group}"
done

pass=( $( echo "$pass" | tr '_' ' ' ) )
password=$( echo "${pass[*]}" | tr ' ' '_' | cut -c 1-$(( length -1 )) )

printf -- "%s" "${password%_}"

