#!/usr/bin/env bash
set -Eeuo pipefail

function find_secret() {
	local secret_name="${1?You must pass in a secret name to find_secret}"
	if ! security find-generic-password -s "$secret_name" -a "$(whoami)" -w; then
		echo >&2 "Unable to find secret $secret_name"
		exit 1
	fi
}

function main() {
	local secret_name="${1?You must pass in a secret name to $0}"
	find_secret "$secret_name"
}

main "${@}"
