#!/usr/bin/env bash
set -Eeuo pipefail

function find_secret() {
    local secret_name="${1?You must pass in a secret name to find_secret}"
    security find-generic-password -s "$secret_name" -a "$(whoami)" -w
}

function main() {
    local secret_name="${1?You must pass in a secret name to $0}"
    find_secret "$secret_name"
}

main "${@}"
