#!/usr/bin/env bash

set -euo pipefail

function open(){
    if which open &>/dev/null; then
        command open "${@}";
    elif which xdg-open &>/dev/null; then
        command xdg-open "${@}";
    else
        echo "open: ${@}"
    fi
}

urls=$( git remote | xargs -I{} git remote get-url {} )

if url=$( echo "$urls" | grep dev.azure.com  | head -n 1 ); then
    # example: git@ssh.dev.azure.com:v3/bushelpowered/terraform/unified-iac

    read org project repo < <( echo "$url" | rev | cut -d/ -f1-3 | rev | tr '/' ' ' );
    open "https://dev.azure.com/$org/$project/_git/$repo/pullrequestcreate?sourceRef=$( git branch --show-current )"

elif url=$( echo "$urls" | grep 'git@bitbucket.org'  | head -n 1 ); then
    # example: git@bitbucket.org:myriadmobile/systems-utils.git

    urlPath=$( echo "$url" | cut -d: -f2 | sed 's/\.git.*$//' )
    open "https://bitbucket.org/${urlPath}/pull-requests/new?source=$( git branch --show-current )&t=1"
elif url=$( echo "$urls" | grep 'git@github.com'  | head -n 1 ); then
    # src: git@github.com:oliverisaac/go-azuredevops.git
    # goal: https://github.com/oliverisaac/go-azuredevops/pull/new/fix-azdo-changecounts-api-differences

    urlPath=$( echo "$url" | cut -d: -f2 | sed 's/\.git.*$//' )
    open "https://github.com/$urlPath/pull/new/$( git branch --show-current )"
else
    >&2 echo "Not in an azdo backed repo: $urls"
    exit 1
fi
