#!/usr/bin/env bash

set -e
set -u
set -o pipefail

force_flag=""
if [[ $1 == "-f" ]] || [[ $1 == "--force" ]]; then
    force_flag="--force"
    shift
fi

remote=${1:-origin}

curr_branch=$( git rev-parse --abbrev-ref HEAD )

if [[ $curr_branch == "" ]]; then
    echo "Not in a git repo!" >&2
    exit 12
fi

upstream=$( git branch --list --format '%(upstream)' "$curr_branch" )

flag=""
if [[ $upstream == "" ]]; then
    flag="--set-upstream"
    echo "Setting upstream $remote to $curr_branch..." >&2
fi

git push ${force_flag} ${flag} "$remote" "$curr_branch"
