#!/usr/bin/env bash

urlencode() {
  local string="${@}"
  local strlen=${#string}
  local encoded=""
  local pos c o

  for (( pos=0 ; pos<strlen ; pos++ )); do
     c=${string:$pos:1}
     case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
     esac
     encoded+="${o}"
  done
  echo "${encoded}"    
}

if [[ $# -gt 0 ]]; then
    urlencode "${@}"
else
    while read -r line || [[ -n "$line" ]]; do
        urlencode "$line"
    done
fi
