#!/usr/bin/env bash

xkcdpass(){
    local count="${1:-5}"
    local divider="${2:- }"

    wordfile=/tmp/wordlist.lst.txt

    if ! [[ -e "$wordfile" ]]; then
        if ! curl --silent --fail "https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt" > "$wordfile"; then
            >&2 echo "Failed to download the wordlist"
            exit 1
        fi
    fi

    function roll_dice(){
        roll=""
        for (( i=0; i<5; i++ )); do
            roll="$roll$(( RANDOM % 6 + 1 ))"
        done
        echo "$roll"
    }

    for (( i=0; i<$count; i++ )); do
        word=$( roll_dice )
        grep -w "$word" "$wordfile"
    done | awk '{print $2}' | tr '\n' " " | sed -e 's/ $//' | tr ' ' "$divider"
}

xkcdpass "${@}" | tee /dev/stderr | pbcopy
