# from: https://github.com/marketplace/actions/simple-version

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}
  push:
    branches:
      - main

name: Add release tag to main

jobs:
  tag:
    name: Add release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version and version code
        uses: xom9ikk/version-by-tag@v1
        id: version_by_tag
        with:
          offset: 1
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{steps.version_by_tag.outputs.tag}}`,
              sha: context.sha
            })
